AllCops:
  DisplayCopNames: true

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Metrics/MethodLength:
  Max: 20
